# Generated by Django 5.2.7 on 2025-10-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_restructure_and_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
