"""
Django settings for ProiectDjango project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import logging

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-*hx38fn!24wl+$vl)21x0u)-^wv2zteu2jalu_xehdhf9m7#3_'
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"]


INSTALLED_APPS = [
    "accounts",
    "hardware",
    "core",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'hardware.middleware.RequestLoggingMiddleware',
]

ROOT_URLCONF = 'ProiectDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hardware.context_processors.categories_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProiectDjango.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'ro-ro'

TIME_ZONE = 'Europe/Bucharest'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:profile"
N_MAX_403 = 5

CLEANUP_UNCONFIRMED_MINUTES = 2
NEWSLETTER_DAY = "marti"
NEWSLETTER_HOUR = 10
NEWSLETTER_MIN_AGE_MINUTES = 30
LOG_CLEANUP_INTERVAL_MINUTES = 15
REQUESTLOG_RETENTION_DAYS = 14
PROMO_CLEANUP_DAY = "vineri"
PROMO_CLEANUP_HOUR = 9


ADMINS = [
    ("Admin1", "admin1@example.com"),
    ("Admin2", "admin2@example.com"),
]
DEFAULT_FROM_EMAIL = "no-reply@magazin-hardware.ro"
SERVER_EMAIL = "server@magazin-hardware.ro"


class LevelFilter(logging.Filter):
    def __init__(self, level):
        super().__init__()
        if isinstance(level, str):
            level = logging._nameToLevel.get(level, level)
        self.level = level

    def filter(self, record: logging.LogRecord) -> bool:
        return record.levelno == self.level


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s",
        },
        "simple": {
            "format": "%(levelname)s %(message)s",
        },
    },
    "filters": {
        "debug_only": {"()": "ProiectDjango.settings.LevelFilter", "level": "DEBUG"},
        "info_only": {"()": "ProiectDjango.settings.LevelFilter", "level": "INFO"},
        "warning_only": {"()": "ProiectDjango.settings.LevelFilter", "level": "WARNING"},
        "error_only": {"()": "ProiectDjango.settings.LevelFilter", "level": "ERROR"},
        "critical_only": {"()": "ProiectDjango.settings.LevelFilter", "level": "CRITICAL"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "WARNING",
            "formatter": "simple",
        },
        "debug_file": {
            "class": "logging.FileHandler",
            "level": "DEBUG",
            "filename": str(BASE_DIR / "debug.log"),
            "formatter": "verbose",
            "filters": ["debug_only"],
        },
        "info_file": {
            "class": "logging.FileHandler",
            "level": "INFO",
            "filename": str(BASE_DIR / "info.log"),
            "formatter": "verbose",
            "filters": ["info_only"],
        },
        "warning_file": {
            "class": "logging.FileHandler",
            "level": "WARNING",
            "filename": str(BASE_DIR / "warning.log"),
            "formatter": "verbose",
            "filters": ["warning_only"],
        },
        "error_file": {
            "class": "logging.FileHandler",
            "level": "ERROR",
            "filename": str(BASE_DIR / "error.log"),
            "formatter": "verbose",
            "filters": ["error_only"],
        },
        "critical_file": {
            "class": "logging.FileHandler",
            "level": "CRITICAL",
            "filename": str(BASE_DIR / "critical.log"),
            "formatter": "verbose",
            "filters": ["critical_only"],
        },
    },
    "loggers": {
        "django": {
            "handlers": [
                "console",
                "debug_file",
                "info_file",
                "warning_file",
                "error_file",
                "critical_file",
            ],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
